import React from 'react';
import PropTypes from 'prop-types';
import Flag from 'react-flagkit';
const flags = (props) => {
  const countryNames = [
    'Austrija',
    'Belgija',
    'Kroatija',
    'Čekija',
    'Danija',
    'Anglija',
    'Suomija',
    'Prancūzija',
    'Vokietija',
    'Vengrija',
    'Italija',
    'Olandija',
    'Makedonija',
    'Lenkija',
    'Portugalija',
    'Rusija',
    'Škotija',
    'Slovakija',
    'Ispanija',
    'Švedija',
    'Šveicarija',
    'Turkija',
    'Ukraina',
    'Velsas',
    'Kataras',
    'Ekvadoras',
    'Senegalas',
    'Iranas',
    'JAV',
    'Argentina',
    'Saudo Arabija',
    'Meksika',
    'Australija',
    'Tunisas',
    'Kosta Rika',
    'Japonija',
    'Kanada',
    'Marokas',
    'Brazilija',
    'Serbija',
    'Kamerūnas',
    'Gana',
    'Urugvajus',
    'Pietų Korėja',
    'Albanija',
    'Slovėnija',
    'Rumunija',
    'Sakartvelas',
  ];
  const countrySymbols = [
    'AT',
    'BE',
    'HR',
    'CZ',
    'DK',
    'GB-ENG',
    'FI',
    'FR',
    'DE',
    'HU',
    'IT',
    'NL',
    'MK',
    'PL',
    'PT',
    'RU',
    'GB-SCT',
    'SK',
    'ES',
    'SE',
    'CH',
    'TR',
    'UA',
    'GB-WLS',
    'QA',
    'EC',
    'SN',
    'IR',
    'US',
    'AR',
    'SA',
    'MX',
    'AU',
    'TN',
    'CR',
    'JP',
    'CA',
    'MA',
    'BR',
    'RS',
    'CM',
    'GH',
    'UY',
    'KR',
    'AL',
    'SI',
    'RO',
    'GE',
  ];
  const index = countryNames.indexOf(props.countryName);
  return <Flag country={countrySymbols[index]} size={props.size ?? 75} />;
};

flags.propTypes = {
  countryName: PropTypes.string,
  size: PropTypes.number,
};

export default flags;
